-- ============================================================
-- AI Video Editing Service — Supabase Tables
-- Crown Media Group | All Glory to Jesus Global LLC
--
-- Run at: https://pcikjtzvruvavaduawes.supabase.co
--         → SQL Editor → New Query → Run All
--
-- After running SQL:
--   1. Go to Storage → New bucket
--   2. Name: video-uploads
--   3. Private: ON (do NOT make public)
--   4. Max file size: 500 MB
--   5. Allowed MIME types: video/mp4,video/quicktime,video/webm,video/mov
-- ============================================================


-- ============================================================
-- TABLE 1: video_projects
-- One row per client video editing job
-- ============================================================
CREATE TABLE IF NOT EXISTS video_projects (
  id                UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at        TIMESTAMPTZ DEFAULT NOW(),
  updated_at        TIMESTAMPTZ DEFAULT NOW(),

  -- Client info (client_id optional — links to existing clients table)
  client_id         UUID REFERENCES clients(id) ON DELETE SET NULL,
  client_name       TEXT NOT NULL,
  client_email      TEXT NOT NULL,
  business_name     TEXT NOT NULL,

  -- Project metadata
  project_title     TEXT,
  video_type        TEXT CHECK (video_type IN (
                      'reel', 'short', 'promo', 'testimonial', 'product', 'event', 'ad'
                    )),
  target_platforms  TEXT[] DEFAULT '{}',
  notes             TEXT,

  -- Upload info
  raw_video_url     TEXT,           -- Supabase Storage path OR external URL
  raw_video_name    TEXT,
  raw_file_size_mb  FLOAT,
  upload_method     TEXT DEFAULT 'drive_link' CHECK (upload_method IN (
                      'portal', 'drive_link', 'dropbox', 'email'
                    )),
  drive_link        TEXT,           -- Google Drive / Dropbox shared link

  -- Processing status (the pipeline)
  status            TEXT DEFAULT 'uploaded' CHECK (status IN (
                      'uploaded',       -- raw video received, waiting
                      'processing',     -- King editing in CapCut / ffmpeg running
                      'ready_review',   -- edited video uploaded, awaiting King approval
                      'approved',       -- King approved edit + captions
                      'scheduled',      -- approved, scheduled to post
                      'posted',         -- live on all platforms
                      'delivered',      -- client notified, case study documented
                      'rejected'        -- sent back for revision
                    )),

  -- King review
  king_notified     BOOLEAN DEFAULT FALSE,
  king_notes        TEXT,
  approved_at       TIMESTAMPTZ,

  -- Edited deliverable
  edited_video_url  TEXT,           -- final file path in Supabase Storage
  thumbnail_url     TEXT,

  -- Scheduling
  scheduled_post_at TIMESTAMPTZ,
  posted_at         TIMESTAMPTZ,

  -- Manual fallback flags (OpusClip / CapCut not available)
  needs_capcut      BOOLEAN DEFAULT TRUE,
  manual_edit_notes TEXT,

  -- Revenue tracking (Dave Ramsey compliance)
  invoice_amount    INTEGER,        -- in cents (e.g. 30000 = $300.00)
  tax_set_aside     INTEGER,        -- 27% of invoice_amount
  revenue_month     TEXT            -- YYYY-MM for monthly report grouping
);

-- Auto-update updated_at on every change
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS video_projects_updated_at ON video_projects;
CREATE TRIGGER video_projects_updated_at
  BEFORE UPDATE ON video_projects
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- Indexes
CREATE INDEX IF NOT EXISTS idx_vp_status ON video_projects(status);
CREATE INDEX IF NOT EXISTS idx_vp_client ON video_projects(client_id);
CREATE INDEX IF NOT EXISTS idx_vp_month  ON video_projects(revenue_month);
CREATE INDEX IF NOT EXISTS idx_vp_scheduled ON video_projects(scheduled_post_at);


-- ============================================================
-- TABLE 2: video_platform_posts
-- One row per platform per video project
-- Generated by Claude (claude-sonnet-4-6)
-- ============================================================
CREATE TABLE IF NOT EXISTS video_platform_posts (
  id                UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at        TIMESTAMPTZ DEFAULT NOW(),

  project_id        UUID NOT NULL REFERENCES video_projects(id) ON DELETE CASCADE,
  platform          TEXT NOT NULL CHECK (platform IN (
                      'instagram', 'tiktok', 'facebook', 'youtube', 'x', 'threads'
                    )),

  -- Claude-generated content
  caption           TEXT NOT NULL,
  hashtags          TEXT,
  platform_title    TEXT,           -- YouTube/TikTok title
  cta_text          TEXT,

  -- Post lifecycle
  status            TEXT DEFAULT 'draft' CHECK (status IN (
                      'draft', 'approved', 'scheduled', 'posted', 'failed', 'skipped'
                    )),
  scheduled_at      TIMESTAMPTZ,
  posted_at         TIMESTAMPTZ,

  -- External IDs
  buffer_post_id    TEXT,           -- Buffer scheduling ID (YouTube/X)
  platform_post_id  TEXT,           -- Native platform post ID
  post_url          TEXT,

  -- Engagement metrics (updated monthly)
  views             INTEGER DEFAULT 0,
  likes             INTEGER DEFAULT 0,
  comments          INTEGER DEFAULT 0,
  shares            INTEGER DEFAULT 0,
  reach             INTEGER DEFAULT 0,

  -- AI generation metadata
  ai_model          TEXT DEFAULT 'claude-sonnet-4-6',
  generation_prompt TEXT,

  -- Client notified after post
  client_notified   BOOLEAN DEFAULT FALSE,

  UNIQUE(project_id, platform)
);

CREATE INDEX IF NOT EXISTS idx_vpp_project  ON video_platform_posts(project_id);
CREATE INDEX IF NOT EXISTS idx_vpp_status   ON video_platform_posts(status);
CREATE INDEX IF NOT EXISTS idx_vpp_platform ON video_platform_posts(platform);
CREATE INDEX IF NOT EXISTS idx_vpp_scheduled ON video_platform_posts(scheduled_at);


-- ============================================================
-- TABLE 3: video_revenue
-- Monthly revenue rollup per client — Dave Ramsey compliance
-- ============================================================
CREATE TABLE IF NOT EXISTS video_revenue (
  id                UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at        TIMESTAMPTZ DEFAULT NOW(),
  updated_at        TIMESTAMPTZ DEFAULT NOW(),

  revenue_month     TEXT NOT NULL,  -- YYYY-MM
  client_id         UUID REFERENCES clients(id) ON DELETE SET NULL,
  client_name       TEXT NOT NULL,
  business_name     TEXT NOT NULL,

  -- Monthly summary
  project_count     INTEGER DEFAULT 0,
  project_ids       TEXT[],          -- array of video_project UUIDs

  -- Revenue (all in cents — 100 = $1.00)
  gross_revenue     INTEGER DEFAULT 0,
  tax_set_aside     INTEGER DEFAULT 0,   -- 27% of gross (Dave Ramsey 25-30%)
  net_revenue       INTEGER DEFAULT 0,   -- gross - tax_set_aside

  -- Service tier
  service_tier      TEXT CHECK (service_tier IN ('basic', 'standard', 'premium')),
  monthly_rate      INTEGER,             -- contracted rate in cents

  -- Payment
  invoice_sent      BOOLEAN DEFAULT FALSE,
  invoice_paid      BOOLEAN DEFAULT FALSE,
  paid_date         DATE,
  stripe_invoice_id TEXT,

  -- Report tracking
  report_generated  BOOLEAN DEFAULT FALSE,
  report_sent_at    TIMESTAMPTZ,

  UNIQUE(revenue_month, client_id)
);

DROP TRIGGER IF EXISTS video_revenue_updated_at ON video_revenue;
CREATE TRIGGER video_revenue_updated_at
  BEFORE UPDATE ON video_revenue
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE INDEX IF NOT EXISTS idx_vr_month  ON video_revenue(revenue_month);
CREATE INDEX IF NOT EXISTS idx_vr_client ON video_revenue(client_id);


-- ============================================================
-- ROW LEVEL SECURITY — matches existing table pattern
-- ============================================================
ALTER TABLE video_projects       ENABLE ROW LEVEL SECURITY;
ALTER TABLE video_platform_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE video_revenue        ENABLE ROW LEVEL SECURITY;

-- Allow all operations (service role key bypasses RLS anyway,
-- anon key needs these policies for portal/dashboard reads)
CREATE POLICY "video_projects_all"       ON video_projects       FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "video_platform_posts_all" ON video_platform_posts FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "video_revenue_all"        ON video_revenue        FOR ALL USING (true) WITH CHECK (true);


-- ============================================================
-- VERIFICATION QUERY — run after creating tables
-- ============================================================
-- SELECT table_name FROM information_schema.tables
-- WHERE table_schema = 'public' AND table_name LIKE 'video%'
-- ORDER BY table_name;
-- Expected: video_platform_posts, video_projects, video_revenue
