// scrape-emails.js
// Fetches church websites and extracts email addresses from contact pages.
// Outputs a review file — does NOT auto-write to the database.
// After reviewing, run apply-emails.js to apply confirmed emails.

const XLSX = require('xlsx');
const https = require('https');
const http = require('http');
const path = require('path');
const fs = require('fs');

const XLSX_PATH = path.join(__dirname, 'churches-columbia-sc.xlsx');
const OUTPUT_PATH = path.join(__dirname, 'email-harvest-results.txt');
const TIMEOUT_MS = 5000;

function fetchPage(url) {
  return new Promise((resolve) => {
    const mod = url.startsWith('https') ? https : http;
    const req = mod.get(url, { timeout: TIMEOUT_MS, headers: { 'User-Agent': 'Mozilla/5.0' } }, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        const redirectUrl = res.headers.location.startsWith('http')
          ? res.headers.location
          : new URL(res.headers.location, url).href;
        return fetchPage(redirectUrl).then(resolve).catch(() => resolve(''));
      }
      let body = '';
      res.on('data', (chunk) => { body += chunk; if (body.length > 200000) req.destroy(); });
      res.on('end', () => resolve(body));
    });
    req.on('error', () => resolve(''));
    req.on('timeout', () => { req.destroy(); resolve(''); });
    setTimeout(() => { req.destroy(); resolve(''); }, TIMEOUT_MS + 1000);
  });
}

function extractEmails(html) {
  const matches = html.match(/mailto:([a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,})/gi) || [];
  const found = new Set();
  for (const m of matches) {
    const email = m.replace('mailto:', '').toLowerCase().split('?')[0];
    if (!email.includes('example') && !email.includes('domain') && email.includes('@')) {
      found.add(email);
    }
  }
  return [...found];
}

function inferEmails(website) {
  const domain = website.replace(/^https?:\/\//, '').replace(/\/.*$/, '').toLowerCase();
  return [
    `info@${domain}`,
    `office@${domain}`,
    `pastor@${domain}`,
    `contact@${domain}`,
  ];
}

function normalizeUrl(website) {
  if (!website) return null;
  const w = website.startsWith('http') ? website : `https://${website}`;
  return w.replace(/\/$/, '');
}

async function scrapeChurch(church) {
  const baseUrl = normalizeUrl(church.website);
  if (!baseUrl) return { type: 'SKIP', reason: 'no website' };

  const contactUrls = [
    `${baseUrl}/contact`,
    `${baseUrl}/contact-us`,
    `${baseUrl}/about/contact`,
    baseUrl,
  ];

  for (const url of contactUrls) {
    let html;
    try { html = await fetchPage(url); } catch { continue; }
    if (!html) continue;
    const emails = extractEmails(html);
    if (emails.length > 0) {
      return { type: 'CONFIRMED', emails, url };
    }
  }

  return { type: 'INFERRED', emails: inferEmails(church.website) };
}

async function main() {
  if (!fs.existsSync(XLSX_PATH)) {
    console.error('XLSX not found — run build-church-list.js first');
    process.exit(1);
  }

  const wb = XLSX.readFile(XLSX_PATH);
  const ws = wb.Sheets['Master List'];
  const rows = XLSX.utils.sheet_to_json(ws, { header: 1 });

  // headers: #, Tier, Church Name, Denomination, Address, City, State, ZIP, Phone, Website, Pastor, Email, ...
  const churches = rows.slice(1)
    .filter(r => r[9] && r[9].toString().trim() && (!r[11] || !r[11].toString().trim()))
    .map(r => ({
      name: r[2],
      tier: r[1],
      website: r[9] ? r[9].toString().trim() : '',
      email: r[11] ? r[11].toString().trim() : '',
      pastor: r[10] ? r[10].toString().trim() : '',
    }))
    .filter(c => c.website && !c.email);

  console.log(`\nFound ${churches.length} churches with websites but no email. Scraping...\n`);

  const lines = [
    `Church Email Harvest — ${new Date().toISOString().slice(0, 10)}`,
    `Generated by scrape-emails.js | Crown Media Group`,
    ``,
    `HOW TO USE THIS FILE:`,
    `  - Review each line. Change [APPLY] or [SKIP] as needed.`,
    `  - For INFERRED lines: verify the email is real before marking APPLY.`,
    `  - Then run: node apply-emails.js`,
    ``,
    `FORMAT: CHURCH NAME | EMAIL | [ACTION]`,
    `=`.repeat(80),
    ``,
  ];

  let confirmedCount = 0;
  let inferredCount = 0;
  let skipCount = 0;

  for (let i = 0; i < churches.length; i++) {
    const c = churches[i];
    process.stdout.write(`  [${i + 1}/${churches.length}] ${c.name}...`);
    const result = await scrapeChurch(c);

    const pad = (s) => s.padEnd(45, ' ');

    if (result.type === 'CONFIRMED') {
      confirmedCount++;
      for (const email of result.emails) {
        lines.push(`APPLY | ${pad(c.name)} | ${email} | CONFIRMED (from ${result.url})`);
      }
      process.stdout.write(` FOUND: ${result.emails[0]}\n`);
    } else if (result.type === 'INFERRED') {
      inferredCount++;
      lines.push(`SKIP  | ${pad(c.name)} | ${result.emails[0]} | INFERRED — verify before changing to APPLY`);
      process.stdout.write(` inferred\n`);
    } else {
      skipCount++;
      lines.push(`SKIP  | ${pad(c.name)} |  | no email found`);
      process.stdout.write(` no email\n`);
    }

    // Brief pause to avoid hammering servers
    await new Promise(r => setTimeout(r, 300));
  }

  lines.push('');
  lines.push('='.repeat(80));
  lines.push(`SUMMARY: ${confirmedCount} confirmed | ${inferredCount} inferred | ${skipCount} not found`);
  lines.push(`Total churches with websites scraped: ${churches.length}`);

  fs.writeFileSync(OUTPUT_PATH, lines.join('\n'), 'utf8');
  console.log(`\n✓ Results saved to: email-harvest-results.txt`);
  console.log(`  Confirmed: ${confirmedCount} | Inferred: ${inferredCount} | Not found: ${skipCount}`);
  console.log(`\nReview the file, mark APPLY or SKIP, then run: node apply-emails.js\n`);
}

main().catch(console.error);
