/**
 * shatiea-content.js — Daily AI content generation for Shatiea (Fruit of the Spirit Juice)
 * Runs at 6 AM via standalone-runner.js
 * Generates 5 content pieces + queues for scheduling
 *
 * Usage:
 *   node tools/shatiea-content.js          ← full run
 *   node tools/shatiea-content.js --test   ← generate without scheduling
 */

const path = require('path');
const fs   = require('fs');

// Load env
for (const p of [path.join(__dirname, '../.env'), path.join(__dirname, '.env')]) {
  if (fs.existsSync(p)) {
    fs.readFileSync(p, 'utf8').split('\n').forEach(line => {
      const [k, ...v] = line.split('=');
      if (k && v.length && !process.env[k.trim()]) {
        process.env[k.trim()] = v.join('=').trim().replace(/^["']|["']$/g, '');
      }
    });
  }
}

const IS_TEST = process.argv.includes('--test');
const ROOT    = path.join(__dirname, '..');

const CONTENT_DIR = path.join(ROOT, 'Agency/ops/content');
const LAST_RUN    = path.join(ROOT, 'Agency/ops/content/.shatiea-last-run');
const ANTHROPIC_KEY = process.env.ANTHROPIC_API_KEY;

// ── Brand Constants ───────────────────────────────────────────────────────────

const SHATIEA_BRAND = {
  business: 'Fruit of the Spirit Juice — faith-based juice business, Columbia SC',
  owner: 'Shatiea',
  tone: 'Warm, bold, faith-driven, clean, community-centered',
  colors: 'Health Green #059669, White, Gold accent #CA8A04',
  scripture: 'Galatians 5:22-23 (love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control)',
  target: 'Faith-based health-conscious women and families, Columbia SC and national',
  cta: ['DM to order', 'Order yours today', 'Link in bio', 'Message us to get yours'],
  hashtags: '#FruitOfTheSpirit #FaithAndHealth #JuiceLife #NaturalJuice #ColumbiaEats #HealthyLiving #KingdomHealth #JuiceBar #WellnessByFaith #SCFoodie #FreshJuice #CleanLiving #FruitJuice #ColumbiaScBusiness #BlackOwnedBusiness',
  pillars: ['faith (25%)', 'health education (30%)', 'client testimonials (25%)', 'product showcase (20%)'],
};

// ── Generate content with Claude ──────────────────────────────────────────────

async function generateContent(date) {
  if (!ANTHROPIC_KEY) throw new Error('ANTHROPIC_API_KEY not set');

  const dayOfWeek = new Date(date).toLocaleDateString('en-US', { weekday: 'long' });
  const pillarIdx = Math.floor(Math.random() * 4);
  const focusPillar = SHATIEA_BRAND.pillars[pillarIdx];

  const prompt = `You are the content writer for ${SHATIEA_BRAND.business}.

Brand tone: ${SHATIEA_BRAND.tone}
Scripture anchor: ${SHATIEA_BRAND.scripture}
Target audience: ${SHATIEA_BRAND.target}
Today (${dayOfWeek}) focus pillar: ${focusPillar}

Generate 5 distinct content pieces. Return as JSON only:
{
  "ig_caption": "3-5 lines. Faith hook + product + CTA. End with 3 relevant emojis. Include ${SHATIEA_BRAND.hashtags}",
  "fb_caption": "5-7 lines. More conversational, community-focused. Story-driven. Longer than IG.",
  "x_post": "Under 240 characters. Punchy. Faith-aligned. One strong CTA. No hashtags.",
  "reel_hook": "First 3 seconds spoken hook (scroll-stopper). Then 3-bullet script outline for 30-60 sec Reel.",
  "email_subject": "Subject line + preview text. Curiosity-driven. Faith-forward. Under 50 chars subject."
}`;

  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': ANTHROPIC_KEY,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 2000,
      messages: [{ role: 'user', content: prompt }],
    }),
  });

  const data = await res.json();
  if (data.error) throw new Error(data.error.message);

  const text = data.content?.[0]?.text || '';
  const match = text.match(/\{[\s\S]*\}/);
  if (!match) throw new Error('No JSON in response');
  return JSON.parse(match[0]);
}

// ── Write content brief to file ───────────────────────────────────────────────

function writeBrief(date, content) {
  if (!fs.existsSync(CONTENT_DIR)) fs.mkdirSync(CONTENT_DIR, { recursive: true });
  const file = path.join(CONTENT_DIR, `shatiea-${date}.md`);

  const md = `# Shatiea Content Brief — ${date}

## Instagram Caption
${content.ig_caption}

---

## Facebook Caption
${content.fb_caption}

---

## X / Twitter Post
${content.x_post}

---

## Reel Hook + Script
${content.reel_hook}

---

## Email Subject + Preview
${content.email_subject}

---
_Generated by shatiea-content.js — ${new Date().toISOString()}_
`;

  fs.writeFileSync(file, md);
  return file;
}

// ── Queue in content-scheduler ────────────────────────────────────────────────

function queueContent(date, content) {
  const SCHEDULER_DB = path.join(ROOT, 'Agency/ops/scheduled-posts.json');
  let posts = [];
  if (fs.existsSync(SCHEDULER_DB)) {
    try { posts = JSON.parse(fs.readFileSync(SCHEDULER_DB, 'utf8')); } catch { posts = []; }
  }

  const baseDate = new Date(date + 'T09:00:00');

  // IG at 9AM
  posts.push({
    id: `shatiea-ig-${date}`,
    platform: 'instagram',
    client: 'shatiea',
    content: content.ig_caption,
    scheduledAt: new Date(baseDate.getTime()).toISOString(),
    status: 'scheduled',
  });

  // FB at 11AM
  posts.push({
    id: `shatiea-fb-${date}`,
    platform: 'facebook',
    client: 'shatiea',
    content: content.fb_caption,
    scheduledAt: new Date(baseDate.getTime() + 2 * 60 * 60 * 1000).toISOString(),
    status: 'scheduled',
  });

  // X at 12PM
  posts.push({
    id: `shatiea-x-${date}`,
    platform: 'twitter',
    client: 'shatiea',
    content: content.x_post,
    scheduledAt: new Date(baseDate.getTime() + 3 * 60 * 60 * 1000).toISOString(),
    status: 'scheduled',
  });

  if (!IS_TEST) {
    fs.writeFileSync(SCHEDULER_DB, JSON.stringify(posts, null, 2));
  }

  return posts.slice(-3);
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function run() {
  const date = new Date().toISOString().split('T')[0];
  console.log(`[Shatiea Content] ${IS_TEST ? '[TEST] ' : ''}Generating for ${date}...`);

  try {
    const content = await generateContent(date);
    const file    = writeBrief(date, content);
    const queued  = queueContent(date, content);

    console.log(`[Shatiea Content] Brief written: ${file}`);
    console.log(`[Shatiea Content] Queued ${queued.length} posts`);
    console.log('\n--- CONTENT PREVIEW ---\n');
    console.log('IG:', content.ig_caption.substring(0, 100) + '...');
    console.log('X: ', content.x_post);
    console.log('Reel hook:', content.reel_hook.substring(0, 80) + '...');
    console.log('-----------------------\n');

    if (!IS_TEST) {
      fs.writeFileSync(LAST_RUN, date);
    }

    console.log('[Shatiea Content] Mission complete. Content ready for Shatiea.');
  } catch (e) {
    console.error('[Shatiea Content] ERROR:', e.message);
    process.exit(1);
  }
}

run();
